name: Deploy on Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [master]  # Adjust branches as needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Get full history for better rsync
    
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: Add server to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
    
    # - name: Rsync repository to server
    #   run: |
    #     rsync -avz --delete \
    #       --exclude='.git/' \
    #       --exclude='.github/' \
    #       --exclude='node_modules/' \
    #       --exclude='.env*' \
    #       --exclude='*.log' \
    #       --exclude='*.dev' \
    #       --exclude='*.env' \
    #       ./ ${{ secrets.SSH_USER }}@${{ secrets.SERVER_HOST }}:${{ secrets.DEPLOY_PATH }}
    
    - name: Run post-deployment commands
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
          cd ${{ secrets.DEPLOY_PATH }}
          
          # Example commands - customize these for your needs
          echo "Deployment started at $(date)"

          # sudo chown -R deploy ${{ secrets.DEPLOY_PATH }}
          
          echo "Deployment completed at $(date)"
        EOF