import crypto from 'crypto';

const adjectives = [
  'unhinged',
  'feral',
  'caffeinated',
  'deranged',
  'buggy',
  'chaotic',
  'noisy',
  'fussy',
  'grumpy',
  'crashy',
  'volatile',
  'delusional',
  'hangry',
  'smug',
  'overclocked',
  'deprecated',
  'janky',
  'clueless',
  'zonedout',
  'keyboardmashing',
  'sleepdeprived',
  'hysterical',
  'unstable',
  'ragequitting',
  'memeable',
  'conflicted',
  'existential',
  'loud',
  'sarcastic',
  'snarky',
  'obsessed',
  'pedantic',
  'awkward',
  'malfunctioning',
  'scatterbrained',
  'bootlooped',
  'slightlyevil',
  'overengineered',
  'maliciouscompliant',
  'anxious',
  'debugging',
  'flickering',
  'glitchy',
  'hyperspecific',
  'burntout',
  'ambiguous',
  'recursive',
  'refactored',
  'emojispamming',
  'pinging',
  'yelling',
  'cursemuted',
  '404ing',
  'sweaty',
  'zombiecoded',
  'syntaxed',
  'verbose',
  'cringy',
  'underflowing',
  'unreadable',
  'garbagecollected',
  'hotfixed',
];

const nouns = [
  'turing',
  'hopper',
  'knuth',
  'liskov',
  'backus',
  'lamport',
  'dijkstra',
  'bernerslee',
  'neumann',
  'shannon',
  'mccarthy',
  'ritchie',
  'thompson',
  'cerf',
  'kay',
  'englebart',
  'abiteboul',
  'torvalds',
  'stallman',
  'wirth',
  'tanenbaum',
  'newell',
  'sutherland',
  'baran',
  'milner',
  'hamilton',
  'adelson',
  'spolsky',
  'gosling',
  'stroustrup',
  'nash',
  'chomsky',
  'norvig',
  'zuse',
  'gilbreth',
  'berlekamp',
  'tovalds',
  'brin',
  'page',
  'lovelace',
  'babbage',
  'denning',
  'codd',
  'diffie',
  'hellman',
  'rivest',
  'shamir',
  'adleman',
  'takahashi',
  'raymond',
  'church',
  'steele',
  'sussman',
];

// I used this to generate random invitation codes.
const generateReferralCode = () => {
  const adj = adjectives[Math.floor(Math.random() * adjectives.length)];
  const noun = nouns[Math.floor(Math.random() * nouns.length)];
  const randomBytes = crypto.randomBytes(2).toString('hex');
  return `${adj}-${noun}-${randomBytes}`;
};

export default generateReferralCode;
